### ISSUE TITLE
presentation review

### ISSUE THREAD

**Issue by KylieScharf** [KylieScharf/newportfolio#2]
Total Scores For Team Members
Kylie: 4.5/5 + 3.5/3 (we won the kahoot and got extra credit) = 8/8
Khushi: 4.5/5 + 3.5/3 (we won the kahoot and got extra credit) = 8/8
Daniel: 4.5/5 + 3.5/3 (we won the kahoot and got extra credit) = 8/8
Kevin: 4.5/5 + 3.5/3 (we won the kahoot and got extra credit) = 8/8
Hamza: 4.5/5 + 3.5/3 (we won the kahoot and got extra credit) = 8/8
Comment count(27 comments)

Backlog Issues Based on comments
[change up stylistic element](https://github.com/KylieScharf/newportfolio/issues/5)
[add a feedback page for user interaction](https://github.com/KylieScharf/newportfolio/issues/8)
[change button style](https://github.com/KylieScharf/newportfolio/issues/7)
[add a slideshow for a new style](https://github.com/KylieScharf/newportfolio/issues/9)

**Comment by jm1021** [comment]
Review ticket in zoom
- [ ] Time Box of Design/Issues/Features accomplishment in README.

1 minute of Project
- [ ] Presenting project/ideas
- [ ] Technical highlights
- [ ] Key features planned for N@tM project 

2 minute runtime
- [ ] Show running project
- [ ] Mention anything that shows incorporation of mini lab technicals in project .25 extra
- [ ] Runtime Feature 1
- [ ] Runtime Feature 2
- [ ] Runtime Feature 3

Technical overview
- [ ]  Technical Feature 1
- [ ]  Technical Feature 2
 

- [ ] Be passionate about the technical, WOW factor.

**Comment by JakubPonulak** [comment]
+ We liked the interactive adventure, good implementation of skills while making something fun
+ Code is organized, no unnecessary repetition
+ Each person had specific role, knew what they were doing / what they were supposed to do
- Theme does not fully reflect Wonders of the World

**Comment by shrutiapcsp** [comment]
Positives- very interesting idea for PBL, incorporated numerous techincals
Improvements- more interactive page for the user

**Comment by DistilledVinegar** [comment]
I loved the clever usage of hyperlinks as branchlines for a choose your own adventure type story. The image were also a great compliment to the text, and the code was very well explained. I would suggest maybe improving certain graphical aspects of the site, such as text size and color, font choice, and image borders.

**Comment by Athena9355** [comment]
positives: 
1. I really love your idea of having the buttons on your page where the users will be able to choose the paths that they take and they might survive the simulation. I think this is a brilliant idea as it allows the users to interact with the page. 
2. I like your codes. They are very organized and short, making it easier for the coders and viewers to understand your logic
3. I like that your whole team seems to know what they are doing and have a very clear understanding of how they wrote the code.

Suggestion:
1. maybe you could add other "decorations" to your pages. For example, make other interactive functions or make different background images.

**Comment by ValenReynolds** [comment]
Positives
The area 51 interactive game was very intuiging. The shortcuts in your code are very efficient. I like how interactive it is. Something the group could improve on is a theme to follow through the whole website.
